name: Automate Ruby on Rails

on:
  push:
    branches:
      - 'main'
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and Push Docker Image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev
          docker build -t us-west1-docker.pkg.dev/$GOOGLE_PROJECT/demo/ruby:latest .
          docker push us-west1-docker.pkg.dev/$GOOGLE_PROJECT/demo/ruby:latest

      - name: Deploy to Cloud Run
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud run deploy ruby-app \
            --image us-west1-docker.pkg.dev/resonant-time-438410-r7/demo/ruby@sha256:68ef8705788e84593a3612450a51861f6df7ca0d1e82dde36621eef3e14f7d2d
            --platform managed \
            --region us-west1 \
            --allow-unauthenticated \
            --port 8080

