name: Ruby on Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Define a PostgreSQL service for the database
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: myapp_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/myapp_test"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0 # specify your Ruby version
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Set up database
      run: |
        bin/rails db:create
        bin/rails db:schema:load

    - name: Run tests
      run: bundle exec rspec # Or `rails test` if using Minitest
